permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Fatima Khan"
  description: |
    My love for art and creativity is what motivated me to pursue a career as a graphic designer. To me, being a designer means that there is no limit. I take pride in my work and want to be able to use my art to visually inspire others.
  font_url: "https://use.typekit.net/zie4gmv.css"
