title: "Button"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required.
patterns:
  basic:
    title: "Main Button"
    description: |
      Default to using the main button.
    width: "12em"
    fields:
      - name: text
        type: string
        example: "E-mail"
      - name: url
        type: string
        example: "/index/"
  button-white:
    title: "White Button"
    description: |
      Can be used when there is a section with a background colour.
    width: "12em"
    fields:
      - name: text
        type: string
        example: "Illustrations"
      - name: url
        type: string
        example: "/index/"
