title: "Button"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required.
patterns:
  basic:
    title: "Main Button"
    description: |
      Default to using the main button.
    width: "12em"
    fields:
      - name: button_text
        type: string
        example: "My Work"
        required: false
      - name: button_url
        type: url
        example: "/work/"
        required: false
