title: "Button"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required.
patterns:
  basic:
    title: "Main Button"
    description: |
      Default to using the main button.
    width: "12em"
    fields:
      - name: text
        type: string
        example: "My Work"
      - name: url
        type: string
        example: "/index/"
