description: |
  Header acts as placeholder for navigation and cart button.
patterns:
  header:
    title: "Header"
    description: |
      Used to navigate through pages on the website.
    background: "--color-accent"
