title: "Sections"
description: |
  Sections are used for organizing large chunks of content.

patterns:
  default-text:
    title: "Default Text Section"
    description: |
      The default text is to be used anywhere on the website where there is a chunk of text that needs to be placed with styling.
    fields:
      - name: header
        type: string
        example: "Case Study"
      - name: subhead
        type: string
        example: "Logo · Branding"
      - name: text1
        type: string
        example: "Hello! My name is Fatima and I am an Ottawa-based graphic designer who seeks to spread diversity. I started off my path into the design world with an interest in visual arts throughout high school. Becoming a graphic designer really helped me discover that I could do more with my illustrations. Since then, I’ve come to love everything that has to do with branding, illustration, packaging, and hand lettering. "
      - name: text2
        type: string
        example: "When I’m not staring at my laptop all day, I enjoy being outdoors, painting, cooking and eating, sleeping, watching TV shows and spending time with my family. My addictions are; Coca Cola, donuts, ice cream and cute animals. "
      - name: text3
        type: string
        example: "As a designer, I believe that we have the opportunity to connect with the rest of the world and help others. I take pride in my work and want to create beautiful designs that can help make a difference. "
  header-text:
    title: "Header Text Style"
    description: |
      The Header Text is to be used anywhere where there is a header on the website.
    fields:
      - name: header
        type: string
        example: "Case Study"
  not-found:
    title: "404 Page"
    description: |
      Used when page cannot be found.
    fields:
      - name: header
        type: string
        example: "404"
      - name: body
        type: string
        example: "WOOPS! LOOKS LIKE THE PAGE YOU REQUESTED CANNOT BE FOUND."
  image:
    title: "Image Section"
    description: |
      Used to embed a 3by2 image in the projects page.
    fields:
      - name: image
        type: url
        example: "placeholder.jpg"
  image-2:
    title: "Image Section"
    description: |
      Used to embed any image in the projects page.
    fields:
      - name: image
        type: url
        example: "mandala.jpg"
  image-3:
    title: "Image Section"
    description: |
      Used to embed any 2by3 image.
    fields:
      - name: image
        type: url
        example: "profile.jpg"
  seo:
    title: "SEO"
    description: |
      The SEO will be used on every layout page as it contains the general data for search engine optimization.
