title: "Sections"
description: |
  Sections are used for organizing large chunks of content.

patterns:
  bio:
    title: "About Section"
    description: |
      Used to write biography about yourself.
  text:
    title: "Text Section"
    description: |
      Used for project description.
    fields:
      - name: header
        type: string
        example: "Case Study"
      - name: description
        type: string
        example: "Tomaso is a small family-owned restaurant that specializes in grilled pizza and panini. The goal was to create a new brand identity that implements the values and nature that the owners bring to their customers, and help them to gain recognition and success in the future.

        To start the process of my research, it was ideal for me to seek what makes them different from any other pizza place. Since they are known for their freshness, wood-fired pizza and grilled smoky flavour, I wanted the new logo to reflect on that. Following the mood board, I started my sketching process and brought together a few variations of what I wanted the logo to represent.

        After choosing two logo concepts that would best fit my target audience, they were presented to a creative team and with the feedback, I was given, my second concept was seen as the most effective for this project."
  image:
    title: "Image Section"
    description: |
      Used to embed a 3by2 image in the projects page.
    fields:
      - name: image
        type: url
        example: "placeholder.jpg"
  image-2:
    title: "Image Section"
    description: |
      Used to embed any image in the projects page.
    fields:
      - name: image
        type: url
        example: "mandala.jpg"
