title: "Sections"
description: |
  Sections are used for organizing large chunks of content.

patterns:
  bio:
    title: "About Section"
    description: |
      Used to write biography about yourself.
  default-text:
    title: "Default Text Section"
    description: |
      The default text is to be used anywhere on the website where there is a chunk of text that needs to be placed with styling.
    fields:
      - name: text1
        type: string
        example: "blaaaah."
      - name: text2
        type: string
        example: "blaaah"
      - name: text3
        type: string
        example: "blaaaah"
      - name: header
        type: string
        example: "Who am I?"
  image:
    title: "Image Section"
    description: |
      Used to embed a 3by2 image in the projects page.
    fields:
      - name: image
        type: url
        example: "placeholder.jpg"
  image-2:
    title: "Image Section"
    description: |
      Used to embed any image in the projects page.
    fields:
      - name: image
        type: url
        example: "mandala.jpg"
