title: "Sections"
description: |
  Sections are used for organizing large chunks of content.

patterns:
  bio:
    title: "About Section"
    description: |
      Used to write bography about yoursel
  text:
    title: "Text Section"
    description: |
      Used for large bodies of text.
    fields:
      - name: text
        type: string
        example: "blah blah blah"
