title: "Banners"
description: |
  Banners are used as a call to action on the main page and on a secondary page.
patterns:
  banner:
    title: "Main Banner"
    description: |
      Main banner with call to action and button linking to projects.
    fields:
      - name: image
        type: string
        example: "banner"
      - name: text
        type: string
        example: "Welcome to my page!."
  banner-two:
    title: "Project Banner"
    description: |
      Banner used for each project page.
    fields:
      - name: class
        type: string
        example: "banner-buchi"
